{
  description = "Networks client setups";
  outputs =
    { self, nixpkgs }: rec
    {
      packages.x86_64-linux.default = nixpkgs.legacyPackages.x86_64-linux.writeShellScriptBin "default" ''echo '${builtins.toJSON lib}' > networks.autogenerated.json'';
      packages.x86_64-darwin.default = nixpkgs.legacyPackages.x86_64-darwin.writeShellScriptBin "default" ''echo '${builtins.toJSON lib}' > networks.autogenerated.json'';
      packages.aarch64-linux.default = nixpkgs.legacyPackages.aarch64-linux.writeShellScriptBin "default" ''echo '${builtins.toJSON lib}' > networks.autogenerated.json'';
      packages.aarch64-darwin.default = nixpkgs.legacyPackages.aarch64-darwin.writeShellScriptBin "default" ''echo '${builtins.toJSON lib}' > networks.autogenerated.json'';
      overlay = final: prev: {
        networksLib = lib;
      };
      lib = import ./networks.nix;
    };
}
