on:
  push:
    branches:
      - "main"
jobs:
  publish:
    permissions:
      id-token: "write"
      contents: "read"
    runs-on: "ubuntu-latest"
    concurrency:  
      cancel-in-progress: false
      group: "main-push"      
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          rolling: true   